# Generated by Django 4.2.1 on 2023-05-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aeroport",
            fields=[
                ("id_aeroport", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Chambres",
            fields=[
                ("id_chambre", models.AutoField(primary_key=True, serialize=False)),
                ("montant", models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name="Clients",
        #     fields=[
        #         ("id_client", models.AutoField(primary_key=True, serialize=False)),
        #         ("nom", models.CharField(max_length=50)),
        #         ("prenom", models.CharField(max_length=50)),
        #         ("telephone", models.CharField(max_length=30)),
        #         ("mail", models.CharField(max_length=50)),
        #     ],
        # ),
        migrations.CreateModel(
            name="Compagnie",
            fields=[
                ("id_compagnie", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FactureChambre",
            fields=[
                ("id_facture", models.AutoField(primary_key=True, serialize=False)),
                ("montant", models.IntegerField()),
                ("date_facture", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FactureVoiture",
            fields=[
                ("id_facture", models.AutoField(primary_key=True, serialize=False)),
                ("montant", models.IntegerField()),
                ("date_facture", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="FactureVol",
            fields=[
                ("id_facture", models.AutoField(primary_key=True, serialize=False)),
                ("montant", models.IntegerField()),
                ("date_facture", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="MarqueVoiture",
            fields=[
                ("id_marque", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ModeleVoiture",
            fields=[
                ("id_modele", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                (
                    "id_marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.marquevoiture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operateur",
            fields=[
                ("id_operateur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TypeChambre",
            fields=[
                ("id_typeChambre", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                ("id_ville", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
            ],
        ),

        # migrations.CreateModel(
        #     name="Voiture",
        #     fields=[
        #         ("vin", models.IntegerField(primary_key=True, serialize=False)),
        #         ("montant", models.IntegerField()),
        #         (
        #             "id_modele",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="AppliDjango.modelevoiture",
        #             ),
        #         ),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name="Societe",
        #     fields=[
        #         ("id_societe", models.AutoField(primary_key=True, serialize=False)),
        #         ("nom", models.CharField(max_length=50)),
        #         (
        #             "id_ville",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="AppliDjango.ville",
        #             ),
        #         ),
        #     ],
        # ),
        
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("id_hotel", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                (
                    "id_ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.ville",
                    ),
                ),
            ],
        ),
        
        migrations.AddField(
            model_name="chambres",
            name="id_hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppliDjango.hotel"
            ),
        ),
        migrations.AddField(
            model_name="chambres",
            name="id_typeChambre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="AppliDjango.typechambre",
            ),
        ),
        migrations.AddField(
            model_name="aeroport",
            name="id_ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="AppliDjango.ville"
            ),
        ),
    ]
