# Generated by Django 4.2.1 on 2023-05-22 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppliDjango", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vol",
            fields=[
                ("id_vol", models.AutoField(primary_key=True, serialize=False)),
                ("date_depart", models.DateTimeField(default=datetime.datetime.now)),
                ("date_arrive", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "aeroport_arrivee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aeroport_arrivee",
                        to="AppliDjango.aeroport",
                    ),
                ),
                (
                    "aeroport_depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aeroport_depart",
                        to="AppliDjango.aeroport",
                    ),
                ),
                (
                    "id_compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.compagnie",
                    ),
                ),
            ],
        ),
    ]
