# Generated by Django 4.2.1 on 2023-05-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppliDjango", "0002_vol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id_client", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("telephone", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                ("PassWord", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Societe",
            fields=[
                ("id_societe", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                (
                    "id_ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.ville",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voiture",
            fields=[
                ("vin", models.AutoField(primary_key=True, serialize=False)),
                ("montant", models.IntegerField()),
                (
                    "id_modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.modelevoiture",
                    ),
                ),
                (
                    "id_societe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.societe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationVol",
            fields=[
                (
                    "num_reservation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_reservation", models.DateField()),
                (
                    "id_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.client",
                    ),
                ),
                (
                    "id_facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.facturevol",
                    ),
                ),
                (
                    "id_vol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.vol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationVoiture",
            fields=[
                (
                    "num_reservation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_reservation", models.DateField()),
                ("date_retour", models.DateField()),
                (
                    "id_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.client",
                    ),
                ),
                (
                    "id_facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.facturevoiture",
                    ),
                ),
                (
                    "vin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.voiture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationChambre",
            fields=[
                (
                    "num_reservation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_reservation", models.DateField()),
                ("duree", models.IntegerField()),
                (
                    "id_chambre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.chambres",
                    ),
                ),
                (
                    "id_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.client",
                    ),
                ),
                (
                    "id_facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.facturechambre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_arrivee", models.DateTimeField()),
                ("heure_depart", models.DateTimeField()),
                (
                    "id_aeroport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.aeroport",
                    ),
                ),
                (
                    "id_vol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppliDjango.vol",
                    ),
                ),
            ],
        ),
    ]
