# Generated by Django 4.2.1 on 2023-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppliDjango", "0003_client_societe_voiture_reservationvol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chambres",
            name="image",
            field=models.ImageField(
                default="../static/img/chambre/chambre2.jpeg", upload_to="../chambres/"
            ),
        ),
    ]
