# Generated by Django 4.2.1 on 2023-05-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppliDjango", "0004_chambres_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chambres",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="../chambres/"),
        ),
    ]
