# Generated by Django 4.2.1 on 2023-05-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppliDjango", "0009_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture",
            name="image",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
