# Generated by Django 4.2.1 on 2023-06-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("AppliDjango", "0010_voiture_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservationchambre",
            name="id_facture",
        ),
        migrations.AddField(
            model_name="facturechambre",
            name="num_reservation",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="AppliDjango.reservationchambre",
            ),
            preserve_default=False,
        ),
    ]
